### ISSUE TITLE
remove ellipsis from all field forms

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#118]
The ellipsis is present in all of the geological forms such as station, structure.... and serves absolutely no purpose.

I will remove them but do you want me to add a label next to the delete and save buttons for each form Gab?

**Comment by ghuotvez** [comment]
Good point! 

Yeah, these were introduced back we were planning on adding some extra options when creating a record, like linkage to other tables, favorites and some others that I forgot. Then I think it was kept because it keeps the save icon away from the window X button, so a user wouldn't accidently close the form instead of saving it. But the app X button is only displayed on laptops and desktop, in tablet mode we don't see it.

If we remove the ellipsis, and add the labels, we might as well switch the order, keeping the save button away from the close of the app? That would also feel more right in my opinion.

**Comment by jameljoseph** [comment]
How do I add the label for the button?  I tried and it didn't work, but I see photo has labels and when I go into the XAML code I don't see anything different.  I have removed the ellipsis and added some code to make it look nice when the labels are in.

**Comment by ghuotvez** [comment]
Alright, that's nice! Thanks for that Jamel. All seems fine!

Found a little glitch though. Only when taking a first station, the bottom bar still shows map page icons and color. Taking a 2nd station fixes it:
![image](https://user-images.githubusercontent.com/19910413/148240978-d7ea1c8d-682d-4c95-beb2-8bb72e6d3396.png)

**Comment by jameljoseph** [comment]
very strange.  Ill check that out too

**Comment by jameljoseph** [comment]
ok i fixed it.  I will upload it for you to view

**Comment by jameljoseph** [comment]
Hey Gab, when you are in visual studio and open up mappage.xaml in designer mode, do you notice the bottom bar is white?  When I build and load the app, it is normal, but in designer mode it is white for me.

**Comment by ghuotvez** [comment]
I do, it's the default "watermark" to state copyright from ESRI. It's white but on load I think it's made transparent by our style.xaml.

**Comment by ghuotvez** [comment]
I'm having a hard time building the app. I finally got a dev license on Microsoft so I can upload the app on Microsoft Store. When I tried it was asking for admin rights and the package got tangled up between my admin and normal user and it's now all locked up . Really weird, anyway I trust you that it's fixed, I read the code in the commit. I'll close the issue. Thanks for this!

**Comment by jameljoseph** [comment]
Ok.  I test on the laptop and on the tablet and both worked for me.  Yes it was a simply fix, I just changed issticky to false.
