### ISSUE TITLE
taking a photo in extended mode

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#268]
So with the new mesa tablets, if you switch to extended photo mode and then take a photo, the app crashes

**Comment by AMartin-MB** [comment]
This is also an issue with our Trimble T7 tablets (Win10 22H2; GSC Field App 2.3.18.0).  Default mode functions without issue.

**Comment by jameljoseph** [comment]
Hey Gab, so for this, I get an error Foreign Key constraint failed on line 312:

int success = inDB.Insert(newTableObject);

this is in dataaccess.cs file

**Comment by ghuotvez** [comment]
> Hey Gab, so for this, I get an error Foreign Key constraint failed on line 312:
> 
> int success = inDB.Insert(newTableObject);
> 
> this is in dataaccess.cs file

Yeah, the new geopackage, the way it was built, can't take another foreign key then stationid. By enabling the extended photo mode, we give the app the power to link a photo to something else in the database, like directly a sample or a fossil. Since the geopackage isn't built to accomodate that, the whole thing crashes. In version 1.8 of the next schema I'll fix the foreign key problem and we'll be able to work again on this issue and make it work.

**Comment by jameljoseph** [comment]
Should we comment out the extended mode then?  I noticed 2 foreign keys, RelationID and StationID

**Comment by ghuotvez** [comment]
> Should we comment out the extended mode then? I noticed 2 foreign keys, RelationID and StationID

No, not for now, since I plan to release version 2.4 and schema 1.8 at the same time, the issue will be fixed when we publish everything.

Yeah I know about the keys, not the best thing. Here's the issue #294, once this one is fixed we'll come back to fix current one.

**Comment by ghuotvez** [comment]
> Should we comment out the extended mode then? I noticed 2 foreign keys, RelationID and StationID

thanks for the catch. We'll know directly what to fix when new schema is done.

**Comment by ghuotvez** [comment]
Tested under dev version 2.4 and it now works well. I did update the code in some other issue that fixed this one at the same time.
