### ISSUE TITLE
Traverse Number in Station Form: increment on new day = new traverse#?

### ISSUE THREAD

**Issue by KazShimamura-GSC** [NRCan/GSC-Field-Application#68]
Howdy,
I've been reviewing GanFeld Surficial and  I was testing the GSC Field app. I had a station stop yesterday and traverse# = 1. 

I was testing out manual XY for station entry and then added another station by GPS today. I noticed Traverse# was still 1. Should we auto increment Traverse# for each new day or should we leave it for our users to decide to change it?

**Comment by ghuotvez** [comment]
Now how it is implemented is that if something has been entered within air photo or traverse #, it'll copy the last values and fill them in for the user when station forms pops open.

There is no calculation on traverse number for daily changes.

https://github.com/NRCan/GSC-Field-Application/blob/169275d8365af043929bd574b969811d2e323eb2/GSCFieldApp/ViewModels/StationViewModel.cs#L286

**Comment by ghuotvez** [comment]
I've added a new option in the setting for auto increment of traverse number. I've also implemented the incrementation itself, since it was never done. This is found within the station form and should by default work in bedrock and surficial.

![2022-08-18 14_06_12-GSC Field Application](https://user-images.githubusercontent.com/19910413/185464292-b4cc9543-1ada-49dc-aa1c-d650e26243d0.png)
