### ISSUE TITLE
Back button (upper left corner)

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#71]
Having gone into a record (station, structure, etc.), one can't return to the Field Notes using the Back arrow. The Back arrow does work in other areas such as the About view.  v1.0.170.0.

![image](https://user-images.githubusercontent.com/52049001/80844805-7c13b400-8bbc-11ea-81e5-6349d4b51a85.png)

**Comment by jameljoseph** [comment]
I noticed this as well so I will look into it.

**Comment by jameljoseph** [comment]
Gab, I think we should remove that back button.  If someone is in a form and clicks the back button, we will have to ask the user if they want to save it or discard the data, which is the exact same as the 2 buttons on the top bar.  It doesn't really serve a purpose that I can tell.

**Comment by ghuotvez** [comment]
No you're right. Actually, we used to have 2. There was one right in the form because we're using Template10, but since those forms are brought up in modal mode, it was useless. I think we kept the UWP one on top bar for navigation, but still in the case of the forms it's again useless. Our app isn't too complicated I think to need that arrow and mostly uses modal forms. We could get rid of it for sure, if you can target it.

**Comment by jameljoseph** [comment]
This is fixed now, but since very little code was changed, I will commit the change with the projection text change when that is done.
