### ISSUE TITLE
Modification F_MA/F_MINERAL

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#94]
1. Ajout de champs dans la table F_MA (Pick list à venir):
- stationid
- phase 
- texture
- alteration_facies

Ces modifications de la table F_MA ont été proposées suite à l'intégration des données de Louise Corriveau sur les IOGC dans la FODR. Louise base son interprétation sur les altérations et la table F_MA ne répondait pas complètement à ses besoins. De plus, ces changements ont été testés avec des données de minéralisation provenant du projet métaux critiques. L'utilisation de ses nouveaux champs pourra donc s'appliquer dans les 2 cas altération et minéralisation.

2. Modification des champs dans la table F_MA:
- relationtable  pour   sampleid
- relationid  pour  earthmatid

Un maid sera obligatoirement attaché à une station, mais on garde aussi l'option de pouvoir attacher un maid à un earthmat ou à un sample.

3. Effacer le champ mineral dans la table F_MA.
Le schéma actuel gère les minéraux à 2 endroits dans la table F_MINERAL et dans la table F_MA. Ce n'est pas très intéressant pour l'utilisateur de faire des requêtes aux deux endroits. Tous les minéraux seront gérés dans la table F_MINERAL.

4. Ajout du champ maid dans la table F_MINERAL.
En ajoutant ce champ il sera possible d'attacher un mineral à un maid.
Il est important de souligner que le champ maid et earthmatid sont des clés secondaires et qu'ils ne peuvent pas être remplis en même temps. Si un mineral est attaché à un earthmat il ne peux pas aussi être attaché à un maid, c'est l'un ou l'autre.

Dans l'application,  dans le formulaire F_MA rendre le champ mineral non obligatoire et avoir la possibilité de mettre plusieurs minéraux pour un même maid.
![Schema_F_MA](https://user-images.githubusercontent.com/49729155/118277535-e4b39300-b496-11eb-9e35-c2797fa17c3c.png)

**Comment by ghuotvez** [comment]
After review of the whole issue with Pierre and Annick, we'll keep the original way of doing within F_MINERALIZATION_ALTERATION, which is relationid and relationtable field. With mostly a link to station by default. Adding more relations with more tables is a niche way of doing and might not be useful for everyone on site. We'll keep the new field though, as well as getting mineral out of the table and keeping them within F_MINERAL.

**Comment by ghuotvez** [comment]
After a quick meeting with Pierre

### Summary of needed changes in F_MINERALIZATION_ALTERATION

- New Phase field
- New Alteration facies field
- New Texture/Structure field
- Distribute picklist don't need parents anymore
- Two new minerals to add to picklist

### Summary of needed changes in F_MINERAL

- New parent field going to F_MINERALIZATION_ALTERATION
- New interaction in field notes, being minerals could be created from a selected earth material or alteration.
- Field note will need to show all minerals associated to a station rather than parse them based on parent.
- Add "M" prefix to all new created minerals (e.g. 22GHV0001AM01 would be mineral 1 of first earth mat of first station)
